# Generated by Django 2.0.3 on 2018-06-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='content1',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='photo',
            new_name='photo1',
        ),
        migrations.AddField(
            model_name='post',
            name='content2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='content3',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='photo2',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='photo3',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
